(lang dune 3.16)

(name stdlib320)

(generate_opam_files true)

(source
 (github alvinz23/cs320-fall-2024-private))

(package
 (name stdlib320)
 (synopsis "Standard Library for CAS CS 320")
 (depends ocaml dune))
